language: minimal
solution: Duplicati.sln
dotnet: 2.0.0
before_install:
  - sudo apt-get install moreutils
install: ./BuildTools/scripts/travis/travis-install.sh $INSTALL_OPT | ts
script: ./BuildTools/scripts/travis/travis.sh $TRAVIS_BUILD_DIR $TEST_CATEGORIES $ZIPFILE | ts
addons:
  coverity_scan:
    project:
      name: "duplicati/duplicati"
      description: "Duplicati Build submitted via Travis CI"
    notification_email: kenneth@duplicati.com
    build_command_prepend: "msbuild /t:Clean"
    build_command: "msbuild /t:Rebuild"
    branch_pattern: coverity_scan
env:
  global:
    # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
    #   via the "travis encrypt" command using the project repo's public key
    - secure: "ijaQDcVcMo/utuP514FiDZVGR5LJbATWmYDmgRIIaI0YG2Rk6uuJp9XXDXr8sx66JWttPGgs7Htqfy50VKHdr7nsfyCQCRNGmqF+OJeUgAQMj5spxn9A7PZY9+GVhnXoJ06wvYjCv5MPeLBMDK/KpIM5Ny5IG+TKzQy4U7Dyg0riMUT61aqzxSjTGfHZPmaqBICJTzsRmeGHglemFUz/1B4NAN+IeAtXoH9YIfA2LjJfYmMLckPgFQLKN/tQRaGPWXh77y0qVgA++K8UVu5W3yGo3JXBPDdabGgKs9BPlfN5/Ixnkcy6ekAubDA/Aspur9x7/szj4/AnGMY6frNB33nQcnJQZ/51GYKr6CXCmjoJQuWc8ZKdEMqDn3w/kyEzvluSjAsJNRVboeWPE4VfpAeUBsjQ+TuEQi8WXhN8VJgZV7yCkVlZTVbhtOxMPsBiFb74lpWC2iQuWLJv9ED6vyXZVzZhNtfjXNXNZzIwYxbcd7I0ZQ8fmDstFnvBJveJby2ZRpECXTbc03eIUq1SAaVJJY2r47RD1PwVqM3xvUTljIqtKdyIz915mEOjqG1BnCDaiGHYJ4byuDDeIUZO9X70s60Gh4hupZA2Ruup0v7SfYgkto6aNcStd0NYd716Vd7hqXNTp6nu01L5YYJDY4h5sHyBXVXbxCKlUb01kUw="
  general:
    - USAGEREPORTER_Duplicati_LEVEL=none
    - AUTOUPDATER_Duplicati_SKIP_UPDATE=1
    - TMPDIR=$HOME/tmp


# matrix expansion within jobs would be good:
# https://github.com/travis-ci/travis-ci/issues/8295
jobs:
  include:
    - stage: build
      install: ./BuildTools/scripts/travis/install-build.sh

    - stage: unit tests
      env:
        - INSTALL_OPT=NUNIT
        - TEST_CATEGORIES=BulkNormal
        - ZIPFILE=data.zip
      cache:
        directories:
          - $HOME/download/
    - stage: unit tests
      env:
        - INSTALL_OPT=NUNIT
        - TEST_CATEGORIES=BulkNoSize
        - ZIPFILE=data.zip
      cache:
        directories:
          - $HOME/download/
    - stage: unit tests
      env:
        - INSTALL_OPT=NUNIT
        - TEST_CATEGORIES=SVNDataLong,SVNData
        - ZIPFILE=DSMCBE.zip
      cache:
        directories:
          - $HOME/download/
    - stage: unit tests
      env:
        - TEST_CATEGORIES=Border,FILTER,Targeted
        - INSTALL_OPT=NUNIT
    - stage: unit tests
      env:
        - TEST_CATEGORIES=Purge,Serialization,WebApi
        - INSTALL_OPT=NUNIT
    - stage: unit tests
      env:
        - TEST_CATEGORIES=Utility,UriUtility,IO
        - INSTALL_OPT=NUNIT

    - stage: integration tests
      env: INSTALL_OPT=SELENIUM
      script:
        - ./BuildTools/scripts/travis/travis.sh $TRAVIS_BUILD_DIR
        - mono "${TRAVIS_BUILD_DIR}"/Duplicati/GUI/Duplicati.GUI.TrayIcon/bin/Release/Duplicati.Server.exe &
        - python guiTests/guiTest.py | ts
      addons:
        sauce_connect:
          username: $SAUCE_USERNAME
          access_key: $SAUCE_ACCESS_KEY
    - stage: deploy
    # TODO: needs to be conditioned
      script:
        - ./BuildTools/scripts/release.sh
